### ISSUE TITLE
Updation to 4.*

### ISSUE THREAD

**Issue by aqibgatoo** [bueltge/WordPress-Admin-Style#21]
The repo hasn't been updated from some time to incorporate changes from 4.* onwards. Is Some one working on that?

**Comment by bueltge** [comment]
The plugin works also with the version 4.*
Do you have problems, ideas for a new working on the plugin?

**Comment by bueltge** [comment]
I have update the version, new pattern loader for easier to enhance. Inside the test works all examples.
