### ISSUE TITLE
Missing tips

### ISSUE THREAD

**Issue by madvik** [bueltge/WordPress-Admin-Style#23]
Hello,

I submit to you 3 missing tips :

For the 2 columns layout : 
```
<div class="handlediv" title="Click to toggle"><br></div>
```
For toogle the block.

An other 2 column type in category :
```
<div id="col-container">
    <div id="col-right">
        <div class="col-wrap"></div>
    </div><!-- /col-right -->
    <div id="col-left">
        <div class="col-wrap"></div>
</div><!-- /col-left -->
</div>
```
To the place of <br> : 
```
<div class="clear"></div>
```

Bye

**Comment by bueltge** [comment]
Thanks for the hint. It would be fine and easier if you send me a pull request. Is this possible for you?

**Comment by madvik** [comment]
Yes no problem,
I try but, i can's pull
```
fatal: unable to access 'https://github.com/bueltge/WordPress-Admin-Style.git/': The requested URL returned error: 403
```
'''

**Comment by bueltge** [comment]
Thats normal. You should create a fork to your user in github, see the Fork Button and the follow how to:
https://help.github.com/articles/using-pull-requests/

**Comment by madvik** [comment]
Arg, Damned, [Great Scott!](http://en.wikipedia.org/wiki/Great_Scott !)

**Comment by bueltge** [comment]
:+1:

**Comment by bueltge** [comment]
Merge via #24
