### ISSUE TITLE
jQuery Dialog Issue with WordPress 4.1.1

### ISSUE THREAD

**Issue by technofreaky** [bueltge/WordPress-Admin-Style#25]
i have download installed in my wp and went to **wp-admin-jquery-ui** and clicked ***Open Dialog***

its not opening correctly. check the screenshot

![popup](https://cloud.githubusercontent.com/assets/1884287/6966933/d5bfc5fc-d979-11e4-88e6-75ab03b175d6.png)

**Comment by madvik** [comment]
The same error for me in an other plugin.
I think is a problem between WordPress and jQuery.
I correct with changing jquery settings.

**Comment by technofreaky** [comment]
@madvik Could please share what you did ?

**Comment by madvik** [comment]
Turn modal setting to false ( *modal:false*) :
```
jQuery( '#companyRevisionDialog' ).dialog( {
	title: 'modal window',
	width: dWidth,
	maxWidth: dWidth,
	heigth: dHeight,
	maxHeight: dHeight,
	show: false,
	hide: false,
	resizable: true,
	closeOnEscape: true,
	modal: false,
	buttons: { 'Ok': function() {
		jQuery( this ).dialog( 'close' );
	}}
});
```

**Comment by bueltge** [comment]
Thanks for discussion here and help to clear the topic.

**Comment by madvik** [comment]
You're welcome.
