### ISSUE TITLE
Escaping using esc_attr_e() 

### ISSUE THREAD

**Issue by neilgee** [bueltge/WordPress-Admin-Style#26]
Hi Frank, started using your plugin which is great, really helpful.

Question for you on internalization and strings, I noticed in a lot of examples like below...
```
<p><?php esc_attr_e('WordPress started in 2003 with a single bit of code to enhance the typography of everyday writing and with fewer users than you can count on your fingers and toes. Since then it has grown to be the largest self-hosted blogging tool in the world, used on millions of sites and seen by tens of millions of people every day.','wp_admin_style'); ?></p>
```
that text or headings are ecaped with `esc_attr_e` - I thought that this was really for **attribute** use and `_e` for regular text - or does it not matter?

**Comment by bueltge** [comment]
It is also important, that you filter the content, there comes back from a language file. Often you can not validate the content of the .mo File and maybe a translater will include a bad script, as `<script` inside the text. This was include and echo via `_e()` and this is the point, that you should use the  `esc_attr_e()` for escaping text.

More hints: https://css-tricks.com/introduction-to-wordpress-front-end-security-escaping-the-things/

Best wishes.
