### ISSUE TITLE
WordPress Built In Dialog Box For My Plugin

### ISSUE THREAD

**Issue by technofreaky** [bueltge/WordPress-Admin-Style#30]
I want to using wordpress defaults model box in post edit page

[wp-admin/post.php?post=368&action=edit]

Model I wanted : Model I wanted

i tried the following instruction in https://codex.wordpress.org/Javascript_Reference/ThickBox

http://i.stack.imgur.com/nGlNK.png

Code I Entered

<div id="my-content-id" style="display:none;">  <p> This is my hidden content! It will appear in ThickBox when the link is clicked. </p>
</div>

I want to control my model with javascript and also needed tab view in that model like

[Media Model ]

Kindly help me to get this done

**Comment by bueltge** [comment]
maybe this helps you
http://wordpress.stackexchange.com/questions/154330/adding-custom-input-for-data-attribute-in-insert-media-modal

I haven't change this, only the public solutions.

**Comment by technofreaky** [comment]
Thanks for the reply will check it if any issue will get back to you .☺

On Wed, Jul 01, 2015 at 4:53 pm, Frank Bültge < notifications@github.com [notifications@github.com] > wrote:
maybe this helps you

http://wordpress.stackexchange.com/questions/154330/adding-custom-input-for-data-attribute-in-insert-media-modal
[http://wordpress.stackexchange.com/questions/154330/adding-custom-input-for-data-attribute-in-insert-media-modal]

I haven't change this, only the public solutions.

—
Reply to this email directly or view it on GitHub
[https://github.com/bueltge/WordPress-Admin-Style/issues/30#issuecomment-117617107] .[https://github.com/notifications/beacon/ABzAf4eiAL3dEj-Ix1TxRmKVEwTuy7Teks5oY8U8gaJpZM4FPoTn.gif]

**Comment by technofreaky** [comment]
Sorry To Get Back To You Again. This Dose Not Work :(

**Comment by bueltge** [comment]
I have no knowhow, no examples, sorry. Also on WPSE no helpful answer?

**Comment by technofreaky** [comment]
no help full answer only one ans .. which is created using pure html


On Thu, Jul 9, 2015 at 12:58 PM, Frank Bültge <notifications@github.com>
wrote:

> I have no knowhow, no examples, sorry. Also on WPSE no helpful answer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bueltge/WordPress-Admin-Style/issues/30#issuecomment-119855305>
> .
>



-- 

Varun Sridharan
Cell : +91 904 224 8903
Email : varunsridharan23@gmail.com
Website : http://www.varunsridharan.in/
