### ISSUE TITLE
Code for jQuery demo

### ISSUE THREAD

**Issue by madvik** [bueltge/WordPress-Admin-Style#37]
Hello,
It is possible to have the code (css and js) to implemante for have all tools list in the page ?

**Comment by bueltge** [comment]
You find the code always below the examples, click on "••• Show markup and usage" and you see the code. All examples are also inside the directory [`patterns`](https://github.com/bueltge/WordPress-Admin-Style/tree/master/patterns) of the plugin.

**Comment by madvik** [comment]
I d'ont have this link : 
![image](https://cloud.githubusercontent.com/assets/3822529/13321930/41fbdf34-dbd2-11e5-8076-2db0b54952f3.png)

**Comment by bueltge** [comment]
You have right. The topic jquery Demo was not include a source in the result. I have not really read your topic. You find this code in this file [js/jquery-ui-demo.js](https://github.com/bueltge/WordPress-Admin-Style/blob/master/js/jquery-ui-demo.js) and this [css-directory](https://github.com/bueltge/WordPress-Admin-Style/tree/master/css).

**Comment by madvik** [comment]
OK thanks a lot

**Comment by bueltge** [comment]
Welcome.
