### ISSUE TITLE
Check for Updates Failed

### ISSUE THREAD

**Issue by bayareawebpro** [bueltge/wordpress-admin-style#48]
The URL https://raw.github.com/bueltge/WordPress-Admin-Style/master/inc/update.json?checking_for_updates=1&installed_version=1.4.2 does not point to a valid plugin metadata file. HTTP response code is 404 (expected: 200)

Should prob throw a try / catch in there to prevent errors.

**Comment by bueltge** [comment]
I removed the auto update function from the plugin, is not longer supportet. If you update to the last version of the repository you should not get error messages.,
Best.
