### ISSUE TITLE
The admin tab of the plugin does not change tabs

### ISSUE THREAD

**Issue by funcion** [bueltge/wordpress-admin-style#50]
**This is the code:**

```
<h2><?php esc_attr_e( 'Tabs', 'WpAdminStyle' ); ?></h2>
<h2 class="nav-tab-wrapper">
	<a href="#" class="nav-tab">Tab #1</a>
	<a href="#" class="nav-tab nav-tab-active">Tab #2</a>
	<a href="#" class="nav-tab">Tab #3</a>
</h2>
```

When I click on any of the tabs, it sends me to the top of the page.

**Comment by bueltge** [comment]
That's right. This tabs are only for the markup code that you should use for tabs in WP Core design. You should add custom queries or other href attributes to use it for your requirements. I hope this helps you to understand that it not works like tabs in jQuery or other ready usable apps.
