### ISSUE TITLE
Contributing for new WordPress CSS features

### ISSUE THREAD

**Issue by maxviewup** [bueltge/wordpress-admin-style#51]
I have looked into WordPress code that many CSS classes and features was added (CSS3, animations, etc) and the project is missing them. 

I want to contribute but the contribution instructions aren't very clear. Can you tell me what i need to do? An fork and pull request will be fine?

**Comment by bueltge** [comment]
Hi @maxviewup 
thanks for your contribution. 
If you would add new markup and his selectors, add patters to https://github.com/bueltge/wordpress-admin-style/tree/master/patterns The plugin parse this automatically and view it, not more is necessary.

if you will change, enhance current patters, please do it also in the existing patterns. Send a pull request and I will check them to include it.
Best.

**Comment by maxviewup** [comment]
Thanks for the answer. I will do that soon as possible.

**Comment by bueltge** [comment]
Great, thanks in advance.

**Comment by bueltge** [comment]
@maxviewup Have you updates on this issue for us or is not more relevant so that we can close the isse?
