### ISSUE TITLE
2 Columns Layout: static (px)

### ISSUE THREAD

**Issue by x9t9** [bueltge/wordpress-admin-style#52]
In the 2 Columns Layout: static (px) section, it seems that the handle div markup has been changed to a button ( not sure in which version )

Old markup : 
	`<div title="Click to toggle" class="handlediv"><br></div>`

New markup :

```
	<button type="button" class="handlediv" aria-expanded="true" >
	<span class="screen-reader-text">Toggle panel</span>
	<span class="toggle-indicator" aria-hidden="true"></span>
	</button>
```
the current version of the plugin does not display the toggle button .

**Comment by bueltge** [comment]
Thanks for the hint. Maybe you will send a PR?
