### ISSUE TITLE
Gutenberg

### ISSUE THREAD

**Issue by bueltge** [bueltge/wordpress-admin-style#54]
It is necessary to add style guides for the Gutenberg project?

**Comment by proweb** [comment]
It'd be usefull

**Comment by dyrer** [comment]
Is this project still active?

**Comment by bueltge** [comment]
It is. What you miss?

**Comment by dyrer** [comment]
Last update was last year, so I Think this project is active :)

**Comment by bueltge** [comment]
Yes, so currently I see no tasks for any update. The styles are the same and Gutenberg has no single style rules.

**Comment by bueltge** [comment]
We should only link to the documentation, https://developer.wordpress.org/block-editor/designers/
That's all and always maintained.

**Comment by onasipim** [comment]
Maybe add some new screenshots? Would certainly give a more active impression

**Comment by bueltge** [comment]
Why not, with pleasure.
Maybe you will add them, send a Pull Request.
