### ISSUE TITLE
add to wpackagist https://wpackagist.org/

### ISSUE THREAD

**Issue by chrillep** [bueltge/wordpress-admin-style#58]
please add this plugin to wpackagist so i/we can use it with composer. the easier way...

**Comment by bueltge** [comment]
There is, see https://packagist.org/packages/bueltge/wordpress-admin-style

**Comment by bueltge** [comment]
However the plugin is not on wordpress.org so it was more in the context of development. I mean wppackagist.rog is only a mirror of wordpress.org. But the plugin is usable via Composer, see the url above in my first comment.

**Comment by chrillep** [comment]
great! sorry didn't look there. I was a bit to fast 😊🤦‍♂️
