### ISSUE TITLE
any plans to add Github updater support?

### ISSUE THREAD

**Issue by RealUn2ken** [bueltge/wordpress-admin-style#59]
since this plugin is essentially can be just found on Github. it would be helpful if you add support for 
this plugin with [Github Updater](https://github.com/afragen/github-updater/wiki) ?

**Comment by bueltge** [comment]
Thanks @RealUn2ken for your idea. Why not, PR are welcome.

**Comment by madvik** [comment]
:+1:

**Comment by bueltge** [comment]
After reading of this plugin I add the meta tag. Now it should work if you have the https://github.com/afragen/github-updater/ active in your install. Maybe you try them and install an older version of the plugin, like version 1.5.3. Thanks for feedback.

**Comment by bueltge** [comment]
The new version is live, inlclude support for the GH Updater plugin - https://github.com/bueltge/wordpress-admin-style/releases/tag/1.5.5

**Comment by RealUn2ken** [comment]
> The new version is live, include support for the GH Updater plugin - https://github.com/bueltge/wordpress-admin-style/releases/tag/1.5.5

thank you very much
