### ISSUE TITLE
Login wordpress admin

### ISSUE THREAD

**Issue by noorwali111** [bueltge/wordpress-admin-style#63]
Is there any way to hide [How to login wordpress admin panel](https://tutorialform.com/how-to-login-wordpress-admin-panel/) in [Wordpress blogs](https://tutorialform.com) .

Thanks

Noor Wali Baz

**Comment by bueltge** [comment]
I'm not sure in which context is this question to the plugin in this Repo here? Because the plugin is a helper for developers to understand how is it possible to design custom areas with the default design of WP. I will close them.
