### ISSUE TITLE
jQuery features not working

### ISSUE THREAD

**Issue by webzunft** [bueltge/wordpress-admin-style#64]
The features under Admin Style > jQuery UI are not working.

![Bildschirmfoto 2021-08-30 um 11 11 41](https://user-images.githubusercontent.com/2728720/131316167-0b2e90c6-a36b-49e6-a3e1-ff53409c3447.png)

I already fixed a warning for HTTPS sites caused by https://github.com/bueltge/wordpress-admin-style/blob/92c86f8d1ce09b290aaf11123f9b614da2c1371d/inc/WpAdminJqueryUi.php#L758

But that didn’t help. There is no further warning I see and could experiment with.

**Comment by dangerstudios** [comment]
yep totally not working atm :(
