### ISSUE TITLE
[Feature Request]:  Ability to change the colors

### ISSUE THREAD

**Issue by dangerstudios** [bueltge/wordpress-admin-style#65]
### Is your feature request related to a problem?

I cannot change colors via the plugin UI

### Describe the desired solution

Ability to change the colors via the UI

### Describe the alternatives that you have considered

writing my own plugin

### Additional context

not sure if this is already possible

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bueltge** [comment]
Hello @dangerstudios 
I'm not sure that I understand your request. Can you describe what you miss, and what you miss on the plugin? Currently, the plugin list all the default admin color schemes, including the hex-values, not more.

**Comment by dangerstudios** [comment]
I think what I'm really asking is:
How can I make a generator out of this plugin? for example; 
I would like to quickly modify every value this plugin returns via some kind of GUI

**Comment by bueltge** [comment]
The plugin is not a CLI, Generator, it lists only the default Admin area markups and CSS classes. 
I would close this issue because it is not in case of the plugin, okay?

**Comment by dangerstudios** [comment]
Yes no worries, just confirming that this plugin only exists to list the default Admin area markups and CSS classes.

**Comment by bueltge** [comment]
Right. That's the goal.
